### ISSUE TITLE
SecurityFilter to verify applicationTokenId and userTokenId

### ISSUE THREAD

**Issue by sherriff** [Cantara/Whydah-UserAdminService#27]
On each request the applicationTokenId and userTokenId of calling application and user should be verified against STS. Use Commands in SDK to verify tokens against STS. 

Suggest writing this as a servlet filter, SecurityFilter in UIB can be used as a starting point. 

This check seems appropriate in UAS because UAS may expose endpoints which query UIB for a lot of info, but only returns a subset of the data. It is thus difficult to write these checks in UIB as UIB only sees each individual request.

**Comment by sherriff** [comment]
BLOCKED! Need review of paths/endpoints in UAS with Bård and/or Totto before finishing this.

**Comment by totto** [comment]
we do not want to break the public api in 2.1 I think. I suggest we work with the public API for the 2.* versions

**Comment by sherriff** [comment]
Are you talking about UAS or UIB APIs? Was UAS offical in 2.0 (goldfish memory...)? 

UserAuthenticationEndpoint in UIB has the following endpoints: 
/{applicationTokenId}/authenticate/user/
/{applicationTokenId}/authenticate/user/createandlogon

PasswordResource has: 
/password/{applicationtokenid}/reset/username/{username} (GET and POST) 
/password/{applicationtokenid}/reset/username/{username}/newpassword/{token}
/password/{applicationtokenid}/change/{adminUserTokenId}/user/username/{username}

These are at least not identical to the three in UAS: 
/{applicationtokenid}/auth/logon - LogonController (User Login)
/{applicationtokenid}/auth/password/reset/username
/{applicationtokenid}/create_logon_facebook_user (createAndLogonUser)

**Comment by totto** [comment]
Maybe I was too fast as I was thinking of SecurityFilter and Session Verification, which is public STS endpoint.  The reset password API has not been actively distributed as public API, and just exposed as an option in SSOLWA and as a function in UAWA.

**Comment by sherriff** [comment]
Not against keeping the APIs stable. Just wanted some help in deciding _which_ APIs... :)
