### ISSUE TITLE
Security: application/applications - filter away security section

### ISSUE THREAD

**Issue by totto** [Cantara/Whydah-UserAdminService#40]
Avoid exposing application secret and other sensible data to applications which should not have access

- possibly by filtering it away from json from UIB

**Comment by totto** [comment]
use toSecureJson in TypeLib for none safe applicayions and users

**Comment by baardl** [comment]
if (originalServirceToken.getName == Whydah-UAWA...) {
includeSecureJson()
}

**Comment by totto** [comment]
ApplicationService:
 boolean isUAWA(String applicationTokenId, String userTokenId){
        log.trace("Checking isUAWA. applicationTokenId:{} userTokenId:{} ",applicationTokenId, userTokenId);
        // Check UAWA appid on applicationTokenId from STS - @Path("{applicationtokenid}/get_application_id")
